const numberLists = [
  { num: 1, nepali: "१", word: "एक", roman: "ehkk" },
  { num: 2, nepali: "२", word: "दुई", roman: "dhui" },
  { num: 3, nepali: "३", word: "तीन", roman: "tin" },
  { num: 4, nepali: "४", word: "चार", roman: "char" },
  { num: 5, nepali: "५", word: "पाँच", roman: "pach" },
  { num: 6, nepali: "६", word: "छ", roman: "chha" },
  { num: 7, nepali: "७", word: "सात", roman: "saat" },
  { num: 8, nepali: "८", word: "आठ", roman: "ahth" },
  { num: 9, nepali: "९", word: "नौ", roman: "nau" },
  { num: 10, nepali: "१०", word: "दश", roman: "dash" },

  { num: 11, nepali: "११", word: "एघार", roman: "eh gara" },
  { num: 12, nepali: "१२", word: "बाह्र", roman: "bara" },
  { num: 13, nepali: "१३", word: "तेह्र", roman: "tera" },
  { num: 14, nepali: "१४", word: "चौध", roman: "chaudha" },
  { num: 15, nepali: "१५", word: "पन्ध्र", roman: "panra" },
  { num: 16, nepali: "१६", word: "सोह्र", roman: "sohra" },
  { num: 17, nepali: "१७", word: "सत्र", roman: "shatra" },
  { num: 18, nepali: "१८", word: "अठार", roman: "ahthara" },
  { num: 19, nepali: "१९", word: "उन्नाइस", roman: "unnais" },
  { num: 20, nepali: "२०", word: "बीस", roman: "bis" },

  { num: 21, nepali: "२१", word: "एक्काइस", roman: "ekkais" },
  { num: 22, nepali: "२२", word: "बाइस", roman: "bhais" },
  { num: 23, nepali: "२३", word: "तेइस", roman: "tehis" },
  { num: 24, nepali: "२४", word: "चौबीस", roman: "chaubis" },
  { num: 25, nepali: "२५", word: "पच्चीस", roman: "pachis" },
  { num: 26, nepali: "२६", word: "छब्बीस", roman: "chhabis" },
  { num: 27, nepali: "२७", word: "सत्ताइस", roman: "sat tais" },
  { num: 28, nepali: "२८", word: "अठ्ठाइस", roman: "a thais" },
  { num: 29, nepali: "२९", word: "उनन्तिस", roman: "uhnantis" },
  { num: 30, nepali: "३०", word: "तीस", roman: "tis" },

  { num: 31, nepali: "३१", word: "एकतीस", roman: "ektis" },
  { num: 32, nepali: "३२", word: "बत्तीस", roman: "bhattis" },
  { num: 33, nepali: "३३", word: "तेत्तीस", roman: "the tis" },
  { num: 34, nepali: "३४", word: "चौँतीस", roman: "chau tis" },
  { num: 35, nepali: "३५", word: "पैंतीस", roman: "phai tis" },
  { num: 36, nepali: "३६", word: "छत्तीस", roman: "chha tis" },
  { num: 37, nepali: "३७", word: "सैंतीस", roman: "shai tis" },
  { num: 38, nepali: "३८", word: "अठतीस", roman: "athtis" },
  { num: 39, nepali: "३९", word: "उनन्चालीस", roman: "uhn nanchalis" },
  { num: 40, nepali: "४०", word: "चालीस", roman: "cha lis" },

  { num: 41, nepali: "४१", word: "एकचालीस", roman: "ek cha lis" },
  { num: 42, nepali: "४२", word: "बयालीस", roman: "ba ya lis" },
  { num: 43, nepali: "४३", word: "त्रिचालीस", roman: "tri cha lis" },
  { num: 44, nepali: "४४", word: "चवालीस", roman: "cha wa lis" },
  { num: 45, nepali: "४५", word: "पैँतालीस", roman: "phai ta lis" },
  { num: 46, nepali: "४६", word: "छयालीस", roman: "chha ya lis" },
  { num: 47, nepali: "४७", word: "सत्चालीस", roman: "sat cha lis" },
  { num: 48, nepali: "४८", word: "अठचालीस", roman: "ath cha lis" },
  { num: 49, nepali: "४९", word: "उनन्चास", roman: "u nan chas" },
  { num: 50, nepali: "५०", word: "पचास", roman: "pa chas" },

  { num: 51, nepali: "५१", word: "एकाउन्न", roman: "e ka un na" },
  { num: 52, nepali: "५२", word: "बाउन्न", roman: "ba un na" },
  { num: 53, nepali: "५३", word: "त्रिपन्न", roman: "tri pan na" },
  { num: 54, nepali: "५४", word: "चौपन्न", roman: "chau pan na" },
  { num: 55, nepali: "५५", word: "पचपन्न", roman: "pach pan na" },
  { num: 56, nepali: "५६", word: "छपन्न", roman: "chha pan na" },
  { num: 57, nepali: "५७", word: "सन्ताउन्न", roman: "san ta un na" },
  { num: 58, nepali: "५८", word: "अन्ठाउन्न", roman: "an tha un na" },
  { num: 59, nepali: "५९", word: "उनन्साठी", roman: "u nan sa thi" },

  { num: 60, nepali: "६०", word: "साठी", roman: "sa thi" },
  { num: 61, nepali: "६१", word: "एकसठी", roman: "ek sa thi" },
  { num: 62, nepali: "६२", word: "बासठी", roman: "ba sa thi" },
  { num: 63, nepali: "६३", word: "त्रिसठी", roman: "tri sa thi" },
  { num: 64, nepali: "६४", word: "चौसठी", roman: "chau sa thi" },
  { num: 65, nepali: "६५", word: "पैंसठी", roman: "pain sa thi" },
  { num: 66, nepali: "६६", word: "छयसठी", roman: "chha ya sa thi" },
  { num: 67, nepali: "६७", word: "सतसठी", roman: "sat sa thi" },
  { num: 68, nepali: "६८", word: "अठसठी", roman: "ath sa thi" },
  { num: 69, nepali: "६९", word: "उनन्सत्तरी", roman: "u nan sat ta ri" },
  { num: 70, nepali: "७०", word: "सत्तरी", roman: "sat ta ri" },

  { num: 71, nepali: "७१", word: "एकहत्तर", roman: "ek hat tar" },
  { num: 72, nepali: "७२", word: "बहत्तर", roman: "ba hat tar" },
  { num: 73, nepali: "७३", word: "त्रिहत्तर", roman: "tri hat tar" },
  { num: 74, nepali: "७४", word: "चौहत्तर", roman: "chau hat tar" },
  { num: 75, nepali: "७५", word: "पचहत्तर", roman: "pach hat tar" },
  { num: 76, nepali: "७६", word: "छयहत्तर", roman: "chha ya hat tar" },
  { num: 77, nepali: "७७", word: "सतहत्तर", roman: "sat hat tar" },
  { num: 78, nepali: "७८", word: "अठहत्तर", roman: "ath hat tar" },
  { num: 79, nepali: "७९", word: "उनासी", roman: "u na si" },
  { num: 80, nepali: "८०", word: "असी", roman: "a si" },

  { num: 81, nepali: "८१", word: "एकासी", roman: "e ka si" },
  { num: 82, nepali: "८२", word: "बयासी", roman: "ba ya si" },
  { num: 83, nepali: "८३", word: "त्रियासी", roman: "tri ya si" },
  { num: 84, nepali: "८४", word: "चौरासी", roman: "chau ra si" },
  { num: 85, nepali: "८५", word: "पचासी", roman: "pa cha si" },
  { num: 86, nepali: "८६", word: "छयासी", roman: "chha ya si" },
  { num: 87, nepali: "८७", word: "सतासी", roman: "sa ta si" },
  { num: 88, nepali: "८८", word: "अठासी", roman: "a tha si" },
  { num: 89, nepali: "८९", word: "उनान्नब्बे", roman: "u na nan be" },
  { num: 90, nepali: "९०", word: "नब्बे", roman: "nab be" },

  { num: 91, nepali: "९१", word: "एकानब्बे", roman: "e ka nab be" },
  { num: 92, nepali: "९२", word: "बयानब्बे", roman: "ba ya nab be" },
  { num: 93, nepali: "९३", word: "त्रियानब्बे", roman: "tri ya nab be" },
  { num: 94, nepali: "९४", word: "चौरानब्बे", roman: "chau ra nab be" },
  { num: 95, nepali: "९५", word: "पञ्चानब्बे", roman: "pan cha nab be" },
  { num: 96, nepali: "९६", word: "छयानब्बे", roman: "chha ya nab be" },
  { num: 97, nepali: "९७", word: "सतानब्बे", roman: "sa ta nab be" },
  { num: 98, nepali: "९८", word: "अठानब्बे", roman: "a tha nab be" },
  { num: 99, nepali: "९९", word: "उनान्सय", roman: "u na nan sa ya" },
  { num: 100, nepali: "१००", word: "एक सय", roman: "ek sa ya" },
];

export default numberLists;
