const numberLists = [
  { num: 1, nepali: "१", word: "एक", roman: "ek" },
  { num: 2, nepali: "२", word: "दुई", roman: "du i" },
  { num: 3, nepali: "३", word: "तीन", roman: "tin" },
  { num: 4, nepali: "४", word: "चार", roman: "char" },
  { num: 5, nepali: "५", word: "पाँच", roman: "pan ch" },
  { num: 6, nepali: "६", word: "छ", roman: "chha" },
  { num: 7, nepali: "७", word: "सात", roman: "saat" },
  { num: 8, nepali: "८", word: "आठ", roman: "aa th" },
  { num: 9, nepali: "९", word: "नौ", roman: "nau" },
  { num: 10, nepali: "१०", word: "दश", roman: "dash" },

  { num: 11, nepali: "११", word: "एघार", roman: "e gaar" },
  { num: 12, nepali: "१२", word: "बाह्र", roman: "baa hr" },
  { num: 13, nepali: "१३", word: "तेह्र", roman: "te hr" },
  { num: 14, nepali: "१४", word: "चौध", roman: "chau dh" },
  { num: 15, nepali: "१५", word: "पन्ध्र", roman: "pan dhr" },
  { num: 16, nepali: "१६", word: "सोह्र", roman: "so hr" },
  { num: 17, nepali: "१७", word: "सत्र", roman: "sa tra" },
  { num: 18, nepali: "१८", word: "अठार", roman: "a thaar" },
  { num: 19, nepali: "१९", word: "उन्नाइस", roman: "un nais" },
  { num: 20, nepali: "२०", word: "बीस", roman: "bis" },

  { num: 21, nepali: "२१", word: "एक्काइस", roman: "ek kais" },
  { num: 22, nepali: "२२", word: "बाइस", roman: "ba is" },
  { num: 23, nepali: "२३", word: "तेइस", roman: "te is" },
  { num: 24, nepali: "२४", word: "चौबीस", roman: "chau bis" },
  { num: 25, nepali: "२५", word: "पच्चीस", roman: "pa chis" },
  { num: 26, nepali: "२६", word: "छब्बीस", roman: "chha b bis" },
  { num: 27, nepali: "२७", word: "सत्ताइस", roman: "sat tais" },
  { num: 28, nepali: "२८", word: "अठ्ठाइस", roman: "a thais" },
  { num: 29, nepali: "२९", word: "उनन्तिस", roman: "u nan tis" },
  { num: 30, nepali: "३०", word: "तीस", roman: "tis" },

  { num: 31, nepali: "३१", word: "एकतीस", roman: "ek tis" },
  { num: 32, nepali: "३२", word: "बत्तीस", roman: "bat tis" },
  { num: 33, nepali: "३३", word: "तेत्तीस", roman: "tet tis" },
  { num: 34, nepali: "३४", word: "चौँतीस", roman: "chau tis" },
  { num: 35, nepali: "३५", word: "पैंतीस", roman: "pai tis" },
  { num: 36, nepali: "३६", word: "छत्तीस", roman: "chhat tis" },
  { num: 37, nepali: "३७", word: "सैंतीस", roman: "sai tis" },
  { num: 38, nepali: "३८", word: "अठतीस", roman: "a th tis" },
  { num: 39, nepali: "३९", word: "उनन्चालीस", roman: "u nan cha lis" },
  { num: 40, nepali: "४०", word: "चालीस", roman: "cha lis" },

  { num: 41, nepali: "४१", word: "एकचालीस", roman: "ek cha lis" },
  { num: 42, nepali: "४२", word: "बयालीस", roman: "ba ya lis" },
  { num: 43, nepali: "४३", word: "त्रिचालीस", roman: "tri cha lis" },
  { num: 44, nepali: "४४", word: "चवालीस", roman: "cha wa lis" },
  { num: 45, nepali: "४५", word: "पैँतालीस", roman: "pai ta lis" },
  { num: 46, nepali: "४६", word: "छयालीस", roman: "chha ya lis" },
  { num: 47, nepali: "४७", word: "सत्चालीस", roman: "sat cha lis" },
  { num: 48, nepali: "४८", word: "अठचालीस", roman: "a th cha lis" },
  { num: 49, nepali: "४९", word: "उनन्चास", roman: "u nan chas" },
  { num: 50, nepali: "५०", word: "पचास", roman: "pa chas" },

  { num: 59, nepali: "५९", word: "उनन्साठी", roman: "un na sa thi" },
  { num: 60, nepali: "६०", word: "साठी", roman: "sa thi" },

  { num: 69, nepali: "६९", word: "उनन्सत्तरी", roman: "un na sat ta ri" },
  { num: 70, nepali: "७०", word: "सत्तरी", roman: "sat ta ri" },

  { num: 79, nepali: "७९", word: "उनासी", roman: "u na si" },
  { num: 80, nepali: "८०", word: "असी", roman: "a si" },

  { num: 89, nepali: "८९", word: "उनान्नब्बे", roman: "u nan nab be" },
  { num: 90, nepali: "९०", word: "नब्बे", roman: "nab be" },

  { num: 99, nepali: "९९", word: "उनान्सय", roman: "u nan sa ya" },
  { num: 100, nepali: "१००", word: "एक सय", roman: "ek sa ya" },
];
