const numberLists=const nepaliNumbers = [
  { num: 1, nepali: "१", word: "एक", roman: "ek" },
  { num: 2, nepali: "२", word: "दुई", roman: "dui" },
  { num: 3, nepali: "३", word: "तीन", roman: "tin" },
  { num: 4, nepali: "४", word: "चार", roman: "char" },
  { num: 5, nepali: "५", word: "पाँच", roman: "panch" },
  { num: 6, nepali: "६", word: "छ", roman: "chha" },
  { num: 7, nepali: "७", word: "सात", roman: "saat" },
  { num: 8, nepali: "८", word: "आठ", roman: "aath" },
  { num: 9, nepali: "९", word: "नौ", roman: "nau" },
  { num: 10, nepali: "१०", word: "दश", roman: "dash" },

  { num: 11, nepali: "११", word: "एघार", roman: "egaar" },
  { num: 12, nepali: "१२", word: "बाह्र", roman: "baahr" },
  { num: 13, nepali: "१३", word: "तेह्र", roman: "tehr" },
  { num: 14, nepali: "१४", word: "चौध", roman: "chaudh" },
  { num: 15, nepali: "१५", word: "पन्ध्र", roman: "pandhr" },
  { num: 16, nepali: "१६", word: "सोह्र", roman: "sohr" },
  { num: 17, nepali: "१७", word: "सत्र", roman: "satra" },
  { num: 18, nepali: "१८", word: "अठार", roman: "athar" },
  { num: 19, nepali: "१९", word: "उन्नाइस", roman: "unnais" },
  { num: 20, nepali: "२०", word: "बीस", roman: "bis" },

  { num: 21, nepali: "२१", word: "एक्काइस", roman: "ekkais" },
  { num: 22, nepali: "२२", word: "बाइस", roman: "bais" },
  { num: 23, nepali: "२३", word: "तेइस", roman: "teis" },
  { num: 24, nepali: "२४", word: "चौबीस", roman: "chaubis" },
  { num: 25, nepali: "२५", word: "पच्चीस", roman: "pachis" },
  { num: 26, nepali: "२६", word: "छब्बीस", roman: "chabbis" },
  { num: 27, nepali: "२७", word: "सत्ताइस", roman: "sattais" },
  { num: 28, nepali: "२८", word: "अठ्ठाइस", roman: "atthais" },
  { num: 29, nepali: "२९", word: "उनन्तिस", roman: "unantis" },
  { num: 30, nepali: "३०", word: "तीस", roman: "tis" },

  { num: 31, nepali: "३१", word: "एकतीस", roman: "ektis" },
  { num: 32, nepali: "३२", word: "बत्तीस", roman: "battis" },
  { num: 33, nepali: "३३", word: "तेत्तीस", roman: "tettis" },
  { num: 34, nepali: "३४", word: "चौँतीस", roman: "chauntis" },
  { num: 35, nepali: "३५", word: "पैंतीस", roman: "paintis" },
  { num: 36, nepali: "३६", word: "छत्तीस", roman: "chhattis" },
  { num: 37, nepali: "३७", word: "सैंतीस", roman: "saintis" },
  { num: 38, nepali: "३८", word: "अठतीस", roman: "athtis" },
  { num: 39, nepali: "३९", word: "उनन्चालीस", roman: "unanchalis" },
  { num: 40, nepali: "४०", word: "चालीस", roman: "chalis" },

  { num: 41, nepali: "४१", word: "एकचालीस", roman: "ekchalis" },
  { num: 42, nepali: "४२", word: "बयालीस", roman: "bayalis" },
  { num: 43, nepali: "४३", word: "त्रिचालीस", roman: "trichalis" },
  { num: 44, nepali: "४४", word: "चवालीस", roman: "chawalis" },
  { num: 45, nepali: "४५", word: "पैँतालीस", roman: "paintalis" },
  { num: 46, nepali: "४६", word: "छयालीस", roman: "chhayalis" },
  { num: 47, nepali: "४७", word: "सत्चालीस", roman: "satchalis" },
  { num: 48, nepali: "४८", word: "अठचालीस", roman: "athchalis" },
  { num: 49, nepali: "४९", word: "उनन्चास", roman: "unanchas" },
  { num: 50, nepali: "५०", word: "पचास", roman: "pachas" },

  { num: 51, nepali: "५१", word: "एकाउन्न", roman: "ekaunna" },
  { num: 52, nepali: "५२", word: "बाउन्न", roman: "baunna" },
  { num: 53, nepali: "५३", word: "त्रिपन्न", roman: "tripanna" },
  { num: 54, nepali: "५४", word: "चौवन्न", roman: "chauvanna" },
  { num: 55, nepali: "५५", word: "पचपन्न", roman: "pachpanna" },
  { num: 56, nepali: "५६", word: "छपन्न", roman: "chhappanna" },
  { num: 57, nepali: "५७", word: "सन्ताउन्न", roman: "santau nna" },
  { num: 58, nepali: "५८", word: "अन्ठाउन्न", roman: "anthau nna" },
  { num: 59, nepali: "५९", word: "उनन्साठी", roman: "unnasathi" },
  { num: 60, nepali: "६०", word: "साठी", roman: "sathi" },

  { num: 61, nepali: "६१", word: "एकसट्ठी", roman: "eksatthi" },
  { num: 62, nepali: "६२", word: "बैसट्ठी", roman: "baisatthi" },
  { num: 63, nepali: "६३", word: "त्रिसट्ठी", roman: "trisatthi" },
  { num: 64, nepali: "६४", word: "चौसट्ठी", roman: "chausatthi" },
  { num: 65, nepali: "६५", word: "पैँसट्ठी", roman: "paisatthi" },
  { num: 66, nepali: "६६", word: "छैसट्ठी", roman: "chhaisatthi" },
  { num: 67, nepali: "६७", word: "सतसट्ठी", roman: "satsatthi" },
  { num: 68, nepali: "६८", word: "अठसट्ठी", roman: "athsatthi" },
  { num: 69, nepali: "६९", word: "उनन्सत्तरी", roman: "unnasattari" },
  { num: 70, nepali: "७०", word: "सत्तरी", roman: "sattari" },

  { num: 71, nepali: "७१", word: "एकहत्तर", roman: "ekhattar" },
  { num: 72, nepali: "७२", word: "बहत्तर", roman: "bahattar" },
  { num: 73, nepali: "७३", word: "त्रिहत्तर", roman: "trihattar" },
  { num: 74, nepali: "७४", word: "चौहत्तर", roman: "chauhattar" },
  { num: 75, nepali: "७५", word: "पचहत्तर", roman: "pachhattar" },
  { num: 76, nepali: "७६", word: "छयहत्तर", roman: "chhihattar" },
  { num: 77, nepali: "७७", word: "सतहत्तर", roman: "sathattar" },
  { num: 78, nepali: "७८", word: "अठहत्तर", roman: "athhattar" },
  { num: 79, nepali: "७९", word: "उनासी", roman: "unasi" },
  { num: 80, nepali: "८०", word: "असी", roman: "asi" },

  { num: 81, nepali: "८१", word: "एकासी", roman: "ekasi" },
  { num: 82, nepali: "८२", word: "बयासी", roman: "bayasi" },
  { num: 83, nepali: "८३", word: "त्रियासी", roman: "triyasi" },
  { num: 84, nepali: "८४", word: "चौरासी", roman: "chaurasi" },
  { num: 85, nepali: "८५", word: "पचासी", roman: "pachasi" },
  { num: 86, nepali: "८६", word: "छयासी", roman: "chhayasi" },
  { num: 87, nepali: "८७", word: "सतासी", roman: "satasi" },
  { num: 88, nepali: "८८", word: "अठासी", roman: "athasi" },
  { num: 89, nepali: "८९", word: "उनान्नब्बे", roman: "unanabbe" },
  { num: 90, nepali: "९०", word: "नब्बे", roman: "nabbe" },

  { num: 91, nepali: "९१", word: "एकान्नब्बे", roman: "ekanabbe" },
  { num: 92, nepali: "९२", word: "बयान्नब्बे", roman: "bayanabbe" },
  { num: 93, nepali: "९३", word: "त्रियान्नब्बे", roman: "triyanabbe" },
  { num: 94, nepali: "९४", word: "चौरान्नब्बे", roman: "chauranabbe" },
  { num: 95, nepali: "९५", word: "पन्चान्नब्बे", roman: "panchanabbe" },
  { num: 96, nepali: "९६", word: "छयान्नब्बे", roman: "chhayanabbe" },
  { num: 97, nepali: "९७", word: "सन्तान्नब्बे", roman: "santanabbe" },
  { num: 98, nepali: "९८", word: "अन्ठान्नब्बे", roman: "anthaanabbe" },
  { num: 99, nepali: "९९", word: "उनान्सय", roman: "unansaya" },
  { num: 100, nepali: "१००", word: "एक सय", roman: "ek saya" }
];

export default numberLists